-- Create a table for public profiles linked to auth.users
create table public.profiles (
  id uuid references auth.users not null primary key,
  phone_number text unique not null,
  full_name text,
  role text check (role in ('admin', 'sales', 'warranty', 'viewer')) default 'viewer',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;

-- Policies for profiles
create policy "Public profiles are viewable by everyone" on public.profiles
  for select using (true);

create policy "Users can insert their own profile" on public.profiles
  for insert with check (auth.uid() = id);

create policy "Admins can update profiles" on public.profiles
  for update using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    )
  );

-- Products Table
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  image_url text,
  qr_code text unique,
  warranty_period_months int default 12,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.products enable row level security;

-- Everyone can read products
create policy "Products are viewable by everyone" on public.products
  for select using (true);

-- Only Admin or Sales? No, Admin usually adds products.
-- "xoá dữ liệu . chỉ admin đủ quyền thêm sửa xoá." -> Admin can create/edit/delete.
create policy "Admins can insert products" on public.products
  for insert with check (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

create policy "Admins can update products" on public.products
  for update using (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

create policy "Admins can delete products" on public.products
  for delete using (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

-- Orders Table
create table public.orders (
  id bigint generated by default as identity primary key,
  customer_name text,
  customer_phone text,
  total_amount numeric,
  created_by uuid references public.profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.orders enable row level security;

create policy "Auth users can view orders" on public.orders for select using (auth.role() = 'authenticated');

-- Sales and Admin can create orders
create policy "Sales and Admin can create orders" on public.orders
  for insert with check (
    exists (select 1 from public.profiles where id = auth.uid() and role in ('admin', 'sales'))
  );

-- Order Items Table
create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade,
  product_id bigint references public.products(id),
  product_name text, -- Store snapshot of name
  quantity int default 1,
  price_at_sale numeric,
  warranty_duration_months int,
  warranty_end_date timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.order_items enable row level security;

create policy "Auth users can view order items" on public.order_items for select using (auth.role() = 'authenticated');

create policy "Sales and Admin can create order items" on public.order_items
  for insert with check (
    exists (select 1 from public.profiles where id = auth.uid() and role in ('admin', 'sales'))
  );

-- Trigger to create profile on signup (optional, or handle in code)
-- For now, we assume App handles profile creation in detailed setup.
